services:
  - type: web
    name: zynetic-api
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: zynetic-db
          property: connectionString
      - key: DB_SYNCHRONIZE
        value: true

databases:
  - name: zynetic-db
    databaseName: telemetry
    user: zynetic_user
    plan: free
