services:
  - type: web
    name: zynetic-api
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromService:
          type: psql
          name: zynetic-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        fromService:
          type: psql
          name: zynetic-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: psql
          name: zynetic-db
          property: password
      - key: DB_DATABASE
        fromService:
          type: psql
          name: zynetic-db
          property: database
      - key: DB_SYNCHRONIZE
        value: true

databases:
  - name: zynetic-db
    databaseName: telemetry
    user: postgres
    plan: free
