services:
  - type: web
    name: zynetic-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromService: zynetic-db
        property: host
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        fromService: zynetic-db
        property: user
      - key: DB_PASSWORD
        fromService: zynetic-db
        property: password
      - key: DB_DATABASE
        fromService: zynetic-db
        property: database
      - key: DB_SYNCHRONIZE
        value: true

databases:
  - name: zynetic-db
    databaseName: telemetry
    user: postgres
    plan: free
